site_name: PyTexas 2026 Talk & Repo
site_url: https://prosperousheart.github.io/mkdocs-jupyterlite-template-repo/
repo_url: https://github.com/prosperousheart/mkdocs-jupyterlite-template-repo/
edit_uri: blob/main/docs/

nav:
  # - Home: index.md
  - The Talk: index.md
  - Notebook In Root: notebook.ipynb
  - Directory:
      - Notebook In Directory: tmp-ex-dir/notebook.ipynb

extra_css:
  - extra.css

plugins:
  - jupyterlite:
      enabled: true
      notebook_patterns:
        - '*.ipynb'

markdown_extensions:
  - attr_list
