name: Security Checks

on: [push, pull_request]

jobs:
  gitleaks:
    name: Gitleaks
    runs-on: ubuntu-latest
    container:
      image: zricethezav/gitleaks:latest
      options: --entrypoint ""
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Mark repository as safe
      run: git config --global --add safe.directory $GITHUB_WORKSPACE
    - name: Run Gitleaks
      run: gitleaks git . --verbose --redact
      # Uncomment the line below and comment out the above line to switch scan mode
      # run: gitleaks dir . --verbose --redact
